### ISSUE TITLE
Importer status did not update after reimporting successfully

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist_knapsack#789]
reference https://github.com/samvera/bulkrax/issues/974

CSV Importer failed and reported errors. After rerunning and completing successfully, statuses still showed failures.
https://adl.s2.adventistdigitallibrary.org/importers/305

**Comment by ShanaLMoore** [comment]
I just checked on the linked importer above and that status is resolved to complete: 

![Image](https://github.com/user-attachments/assets/5c46780f-9397-434f-9032-02bce3b04fe2)

I wonder if there were unfinished jobs when this was originally reported.

**Comment by jillpe** [comment]
@KatharineV are you still seeing this issue, we think this might be resolved

**Comment by KatharineV** [comment]
I’m at lunch so I just checked on mobile, and I still see the error.


[Image.png]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
